# Generated by Django 3.1 on 2023-07-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sellitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='item_image',
            field=models.ImageField(upload_to='images/sell_buy_products'),
        ),
    ]
