# Generated by Django 3.1 on 2023-07-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230719_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
