# Generated by Django 3.1 on 2023-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230730_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitem',
            name='is_negotiable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
    ]
