# Generated by Django 3.1 on 2023-08-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230809_1742'),
        ('orders', '0031_auto_20230822_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='town',
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
